### ISSUE TITLE
Can you provide libraries for the source code?

### ISSUE THREAD

**Issue by iamlvm** [Debianguru/CoordVNF-SVNF#1]
Thanks for your simulation toolkit,

I am facing a problem when importing the implemented code. 
It shows that I don't have libraries. I have tried to find the libraries but I could not find the libraries correctly. (commons-math3.jar / jun2=2_0_1-sources.zip / JUNG2.jar)
I highly appreciate your help.

**Comment by xiejichao** [comment]
Maybe you need this.
https://sourceforge.net/projects/alevin/files/

**Comment by iamlvm** [comment]
@xiejichao 
![lib](https://user-images.githubusercontent.com/15703029/32818195-2ed1c662-ca05-11e7-800c-d2eababedc6e.png)
I had a look at the ALEVIN simulation tool, but it seems that the "lib" folder does not contain any JAR library files. If you had the files, could you send me? (It was shown in the attached file)

**Comment by xiejichao** [comment]
Sorry，I haven't try this simulation tool yet.
May be you need these things.
Requirements
JUNG 2.0.1 or newer, http://jung.sf.net
JUnit 4.5 or newer, http://www.junit.org
Sun/Oracle JRE 1.7.x or newer

I got these cotents from "https://sourceforge.net/p/alevin/wiki/home/"

**Comment by iamlvm** [comment]
@xiejichao Thanks for your active help, but I actually had an in-depth look at the problem before posting this question. Following the provided instruction to install the ALEVIN simulation, I could not find the libraries.

**Comment by mtill** [comment]
hi

http://jung.sourceforge.net/
https://commons.apache.org/
https://commons.apache.org/proper/commons-cli/
http://commons.apache.org/proper/commons-math/
https://commons.apache.org/proper/commons-collections/
http://glpk-java.sourceforge.net/
http://sndlib.zib.de/home.action

br

**Comment by xiejichao** [comment]
How to deal with this problem.
 “ClassNotFoundException: com.sun.xml.internal.txw2.output.IndentingXMLStreamWriter”.

**Comment by xiejichao** [comment]
“ClassNotFoundException: com.sun.xml.internal.txw2.output.IndentingXMLStreamWriter”.
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8141405

**Comment by mtill** [comment]
please try with oracle java 7 sdk
by the way, even without resolving this issue, the simulation tool should run very well

**Comment by iamlvm** [comment]
I finally run the project successfully in Windows,
1) Java IDE: eclipse-jee-kepler-SR2-Java8
2) Import Alevin-svn (version 2)
        JRE System Library: jdk1.7.0_79
        Libs: [libs.zip](https://github.com/mtill/NFV-Orchestration/files/1516639/libs.zip)
        Change JavaBuildPath of glpk-java.jar
         Java Compiler: 1.8
3) Import CoordVNF-SVNF project
        JRE System Library: jre 1.8.0_111
        Java Compiler: 1.8
=> After running SVNF.java
        cannot create directory: D:\java\workspace\CoordVNF-SVNF\results\2017-11-30 14:56:04 SVNF
        Fix: change this file VNFAlgorithmEvaluation.java:139
              Delete: new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()) + " " +
